/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doancnpm;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
/**
 *
 * @author manng
 */
public class frmmain extends javax.swing.JFrame {

    /**
     * Creates new form frmmain
     */
    public frmmain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        ImageIcon icon = new ImageIcon(getClass().getResource("../image/nen.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BtnNhapDiem = new javax.swing.JButton();
        btnThemHS = new javax.swing.JButton();
        BtnNhapDiem2 = new javax.swing.JButton();
        BtnNhapDiem1 = new javax.swing.JButton();
        BtnNhapDiem3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        QL_LopHoc = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnlds = new javax.swing.JMenuItem();
        QL_NamHoc = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        mnths = new javax.swing.JMenuItem();
        mntc = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnqd = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mntkm = new javax.swing.JMenuItem();
        mntkhk = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItemThayDoiQuyDinh = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mntt = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar3.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý học sinh");

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\Lock.png")); // NOI18N
        jLabel3.setText("UserName");

        jTextField1.setText(" ");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\Key.png")); // NOI18N
        jLabel4.setText("PassWord");

        jButton1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPasswordField1.setText("jPasswordField1");

        jToggleButton1.setText("Cancel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jDesktopPane1.add(jPanel2);
        jPanel2.setBounds(740, 30, 270, 120);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("ĐĂNG NHẬP");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(820, 0, 121, 24);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("PHẦM MỀM QUẢN LÝ HỌC SINH ");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(200, 60, 400, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Nhóm phát triển:");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(110, 120, 135, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("-Trần Nhựt Anh");
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(290, 120, 125, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("-Nguyễn Thiện Hoàng Sang");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(290, 150, 219, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("-Nguyễn Minh Mẫn");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(290, 180, 150, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("-Đoàn Hữu Nhân");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(290, 210, 135, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("-Trương Thành Phát");
        jDesktopPane1.add(jLabel11);
        jLabel11.setBounds(290, 240, 162, 22);

        BtnNhapDiem.setBackground(new java.awt.Color(204, 204, 255));
        BtnNhapDiem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnNhapDiem.setForeground(new java.awt.Color(0, 153, 153));
        BtnNhapDiem.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\Hourglass.png")); // NOI18N
        BtnNhapDiem.setText("TỔNG KẾT");

        btnThemHS.setBackground(new java.awt.Color(204, 204, 255));
        btnThemHS.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnThemHS.setForeground(new java.awt.Color(0, 153, 153));
        btnThemHS.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\Shield 16x16.png")); // NOI18N
        btnThemHS.setText("TIẾP NHẬN ");
        btnThemHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHSActionPerformed(evt);
            }
        });

        BtnNhapDiem2.setBackground(new java.awt.Color(204, 204, 255));
        BtnNhapDiem2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnNhapDiem2.setForeground(new java.awt.Color(0, 153, 153));
        BtnNhapDiem2.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\Create.png")); // NOI18N
        BtnNhapDiem2.setText("NHẬP ĐIỂM");

        BtnNhapDiem1.setBackground(new java.awt.Color(204, 204, 255));
        BtnNhapDiem1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnNhapDiem1.setForeground(new java.awt.Color(0, 153, 153));
        BtnNhapDiem1.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\Danger.png")); // NOI18N
        BtnNhapDiem1.setText("QUY ĐỊNH");

        BtnNhapDiem3.setBackground(new java.awt.Color(204, 204, 255));
        BtnNhapDiem3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnNhapDiem3.setForeground(new java.awt.Color(0, 153, 153));
        BtnNhapDiem3.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\View.png")); // NOI18N
        BtnNhapDiem3.setText("TÌM KIẾM");
        BtnNhapDiem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNhapDiem3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a_181.jpg"))); // NOI18N

        jMenu4.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\User group.png")); // NOI18N
        jMenu4.setText("Quản Trị Viên");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Admin");
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\Computer 16x16.png")); // NOI18N
        jMenu3.setText("Hệ Thống");

        jMenuItem6.setText("QL_Môn Học");
        jMenu3.add(jMenuItem6);

        QL_LopHoc.setText("QL_Lớp");
        QL_LopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QL_LopHocActionPerformed(evt);
            }
        });
        jMenu3.add(QL_LopHoc);

        jMenuItem5.setText("QL_Học Kỳ");
        jMenu3.add(jMenuItem5);

        mnlds.setText("QL_ Khối ");
        mnlds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnldsActionPerformed(evt);
            }
        });
        jMenu3.add(mnlds);

        QL_NamHoc.setText("QL_Năm Học");
        QL_NamHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QL_NamHocActionPerformed(evt);
            }
        });
        jMenu3.add(QL_NamHoc);

        jMenuBar1.add(jMenu3);

        jMenu12.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\Person.png")); // NOI18N
        jMenu12.setText("Quản Lý Học Sinh");

        mnths.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\Create.png")); // NOI18N
        mnths.setText("Tiếp Nhận Học Sinh");
        mnths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnthsActionPerformed(evt);
            }
        });
        jMenu12.add(mnths);

        mntc.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\View.png")); // NOI18N
        mntc.setText("Tra Cứu Hồ Sơ HS ");
        mntc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntcActionPerformed(evt);
            }
        });
        jMenu12.add(mntc);

        jMenuBar1.add(jMenu12);

        jMenu5.setText("Quản Lý Điểm");

        mnqd.setText("Nhập Điểm");
        mnqd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnqdActionPerformed(evt);
            }
        });
        jMenu5.add(mnqd);

        jMenuItem2.setText("Tra Cứu");
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Lập Báo Cáo");

        mntkm.setText("Tổng kết môn");
        mntkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntkmActionPerformed(evt);
            }
        });
        jMenu1.add(mntkm);

        mntkhk.setText("Tổng kết học kỳ");
        mntkhk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntkhkActionPerformed(evt);
            }
        });
        jMenu1.add(mntkhk);

        jMenuBar1.add(jMenu1);

        jMenu13.setIcon(new javax.swing.ImageIcon("D:\\Cong_Nghe_Pham_Mem\\Do_An\\Photo for Design Form\\Pinion.png")); // NOI18N
        jMenu13.setText("Quy Định");

        jMenuItemThayDoiQuyDinh.setText("Thay Đổi Quy Định");
        jMenuItemThayDoiQuyDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThayDoiQuyDinhActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItemThayDoiQuyDinh);

        jMenuBar1.add(jMenu13);

        jMenu2.setText("About");

        mntt.setText("Thông tin nhóm phát triển");
        mntt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnttActionPerformed(evt);
            }
        });
        jMenu2.add(mntt);

        jMenuBar1.add(jMenu2);

        jMenu10.setText("Help");
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnNhapDiem2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNhapDiem1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNhapDiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemHS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNhapDiem3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btnThemHS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnNhapDiem3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(BtnNhapDiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnNhapDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnNhapDiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnthsActionPerformed
        // TODO add your handling code here:
        frmTiepNhanHS ths = new frmTiepNhanHS();
        jDesktopPane1.add(ths);
        ths.setVisible(true);
    }//GEN-LAST:event_mnthsActionPerformed

    private void mntcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntcActionPerformed
        // TODO add your handling code here:
        frmDanhSachHS dshs = new frmDanhSachHS();
        jDesktopPane1.add(dshs);
        dshs.setVisible(true);
    }//GEN-LAST:event_mntcActionPerformed

    private void QL_LopHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QL_LopHocActionPerformed
        // TODO add your handling code here:
       frmQL_Lop lop = new frmQL_Lop();
        jDesktopPane1.add(lop);
        lop.setVisible(true);
    }//GEN-LAST:event_QL_LopHocActionPerformed

    private void mnldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnldsActionPerformed
        // TODO add your handling code here:
        frmLapDSLop lds = new frmLapDSLop();
        jDesktopPane1.add(lds);
        lds.setVisible(true);
    }//GEN-LAST:event_mnldsActionPerformed

    private void mntkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntkmActionPerformed
        // TODO add your handling code here:
        frmBaoCaoMon bcm = new frmBaoCaoMon();
        jDesktopPane1.add(bcm);
        bcm.setVisible(true);
    }//GEN-LAST:event_mntkmActionPerformed

    private void mntkhkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntkhkActionPerformed
        // TODO add your handling code here:
        frmBaoCaoHK bchk = new frmBaoCaoHK();
        jDesktopPane1.add(bchk);
        bchk.setVisible(true);
    }//GEN-LAST:event_mntkhkActionPerformed

    private void mnqdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnqdActionPerformed
        // TODO add your handling code here:
        frmQuyDinh qd = new frmQuyDinh();
        jDesktopPane1.add(qd);
        qd.setVisible(true);
    }//GEN-LAST:event_mnqdActionPerformed

    private void mnttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnttActionPerformed
        // TODO add your handling code here:
        frmAbout ab = new frmAbout();
        jDesktopPane1.add(ab);
        ab.setVisible(true);
    }//GEN-LAST:event_mnttActionPerformed

    private void BtnNhapDiem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNhapDiem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNhapDiem3ActionPerformed

    private void btnThemHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHSActionPerformed
        // TODO add your handling code here:
        frmTiepNhanHS ths = new frmTiepNhanHS();
        jDesktopPane1.add(ths);
        ths.setVisible(true);
    }//GEN-LAST:event_btnThemHSActionPerformed

    private void jMenuItemThayDoiQuyDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThayDoiQuyDinhActionPerformed
        // TODO add your handling code here:
        ThayDoiQuyDinh quydinh = new ThayDoiQuyDinh();
        jDesktopPane1.add(quydinh);
        quydinh.setVisible(true);
    }//GEN-LAST:event_jMenuItemThayDoiQuyDinhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void QL_NamHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QL_NamHocActionPerformed
        // TODO add your handling code here:
        frmQL_NamHoc namhoc = new frmQL_NamHoc();
        jDesktopPane1.add(namhoc);
        namhoc.setVisible(true);
    }//GEN-LAST:event_QL_NamHocActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNhapDiem;
    private javax.swing.JButton BtnNhapDiem1;
    private javax.swing.JButton BtnNhapDiem2;
    private javax.swing.JButton BtnNhapDiem3;
    private javax.swing.JMenuItem QL_LopHoc;
    private javax.swing.JMenuItem QL_NamHoc;
    private javax.swing.JButton btnThemHS;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemThayDoiQuyDinh;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JMenuItem mnlds;
    private javax.swing.JMenuItem mnqd;
    private javax.swing.JMenuItem mntc;
    private javax.swing.JMenuItem mnths;
    private javax.swing.JMenuItem mntkhk;
    private javax.swing.JMenuItem mntkm;
    private javax.swing.JMenuItem mntt;
    // End of variables declaration//GEN-END:variables
}
